version: "4.14.0"

services:
  backend:
    container_name: "ng_backend"
    build: ./back-end
    ports:
      - 3001:3001
    volumes:
      - ./backend:/NG_APP/backend
    environment:
      - PORT=3001
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_HOST=db
      - DB_NAME=NGAPP

  frontend:
    container_name: "ng_frontend"
    build: ./backend:/NG_APP/backend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_HOST=http://localhost:3000

  database:
    image: postgress
    container_name: "ng_postgres_db"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - DB_USER = "postgres"
      - DB_PASS = "admin"
      - DB_NAME = "NGAPP"
    volume: 
      - pgdata/:data/postgres

volumes:
  pgdata:
    driver: local