version: '3'

services:
  backend:
    container_name: 'TRYBE_backend'
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/NG_APP/backend
      - /NG_AP/backend/node_modules
    command: yarn dev  
    environment:
      - PORT=3001
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_HOST=127.0.0.2
      - DB_NAME=NGAPP
      - DB_PORT=5432
    healthcheck:
      test: ['CMD', 'lsof', '-i', ':3001']
      timeout: 10s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
    restart: always

  frontend:
    container_name: 'TRYBE_frontend'
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_HOST = http://frontend:3000
      - REACT_APP_API = http://backend:3001

  database:
    container_name: 'TRYBE_postgres'
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=NGAPP
    restart: 'always'
    healthcheck:
      test: ['CMD', 'dmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
  migration:
    build:
      context: ./backend
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "database:5432",
        "--",
        "yarn",
        "sequelize",
        "db:migrate"
      ]
    links:
      - database
    depends_on:
      - database
    env_file: ./backend/.env
    environment:
      - DB_HOST=database   
networks:
  default:
    # Use a custom driver
    driver: bridge
